{
    'name': 'Hotel Management System',
    'version': '1.0.0',
    'summary': 'Summery',
    'description': 'Description',
    'category': 'Category',
    'author': 'Megi',
    'website': 'www.odoo.com',
    'license': '',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/hotels_view.xml',
        'views/reservations_view.xml',
        'views/customer_view.xml',
        'views/room_type_view.xml',
        'views/rooms_view.xml',
        'views/payment_view.xml',
        'views/receipt_view.xml',
        'views/employees_view.xml',
        'views/review_view.xml',
        'report/receipt_report.xml',
        'wizard/receipt_report_view.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True
}
